# Copyright (C) 2018 - present Juergen Zimmermann, Florian Rusch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# https://eslint.org/docs/user-guide/configuring

---
parser: "@typescript-eslint/parser"

# https://github.com/angular-eslint/angular-eslint
#parser: "@angular-eslint/template-parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true

plugins:
  - "@typescript-eslint"
  - "@angular-eslint"
  - prettier
  - import
  - prefer-arrow
  - regexp
  #- deprecation
  - rxjs
  - cypress

extends:
  # https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js
  - eslint:recommended
  # https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/configs/recommended.js
  - plugin:unicorn/recommended
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json
  - plugin:@typescript-eslint/recommended
  # https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json
  - plugin:@angular-eslint/recommended
  # prettier ueberschreibt vorherige Konfigurationseinstellungen
  - plugin:prettier/recommended
  # https://github.com/cartant/eslint-plugin-rxjs/blob/main/source/configs/recommended.ts
  - plugin:rxjs/recommended
  - prettier
  # https://github.com/import-js/eslint-plugin-import/tree/main/config
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  # https://github.com/jest-community/eslint-plugin-jest#rules
  - plugin:eslint-comments/recommended
  # https://github.com/ota-meshi/eslint-plugin-regexp/blob/master/lib/configs/recommended.ts
  - plugin:regexp/recommended
  # https://github.com/cypress-io/eslint-plugin-cypress/blob/master/lib/config/recommended.js
  - plugin:cypress/recommended

env:
  browser: true
  node: true
  es2020: true
  cypress/globals: false

rules:
  "@angular-eslint/component-max-inline-declarations": error
  "@angular-eslint/component-selector":
    - error
    - type: element
      prefix: hs
      style: kebab-case
  "@angular-eslint/directive-selector":
    - error
    - type: attribute
      prefix: hs
      style: camelCase
  "@angular-eslint/no-empty-lifecycle-method": error
  "@angular-eslint/no-forward-ref": error
  "@angular-eslint/no-input-prefix": error
  "@angular-eslint/no-lifecycle-call": error
  "@angular-eslint/no-pipe-impure": error
  "@angular-eslint/no-queries-metadata-property": error
  # https://alligator.io/angular/change-detection-strategy
  #"@angular-eslint/prefer-on-push-component-change-detection": error
  "@angular-eslint/prefer-output-readonly": error
  "@angular-eslint/relative-url-prefix": error
  "@angular-eslint/sort-ngmodule-metadata-arrays": "error"
  "@angular-eslint/use-component-selector": error
  "@angular-eslint/use-component-view-encapsulation": error
  "@angular-eslint/use-injectable-provided-in": error
  "@angular-eslint/use-lifecycle-interface": error

  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules
  "@typescript-eslint/array-type":
    - error
    - default: array
  "@typescript-eslint/await-thenable": error
  "@typescript-eslint/ban-ts-comment": error
  "@typescript-eslint/ban-tslint-comment": error
  "@typescript-eslint/brace-style": error
  "@typescript-eslint/comma-dangle":
    - error
    - always-multiline
  "@typescript-eslint/comma-spacing": error
  "@typescript-eslint/consistent-generic-constructors": error
  "@typescript-eslint/consistent-indexed-object-style": error
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint/default-param-last": error
  "@typescript-eslint/dot-notation": error
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/func-call-spacing": error
  "@typescript-eslint/keyword-spacing": off
  "@typescript-eslint/lines-between-class-members": error
  # angular-eslint recommended
  #"@typescript-eslint/member-ordering": error
  "@typescript-eslint/method-signature-style": error
  "@typescript-eslint/naming-convention":
    - error
    - selector: default
      format:
        - camelCase
    - selector: variable
      format:
        - camelCase
        - UPPER_CASE
    - selector: parameter
      format:
        - camelCase
      leadingUnderscore: allow
    - selector: memberLike
      format:
        - camelCase
    - selector: property
      modifiers:
        - private
      format:
        - camelCase
      leadingUnderscore: allow
    - selector: classProperty
      modifiers:
        - private
        - static
        - readonly
      format:
        - UPPER_CASE
    - selector: enumMember
      format:
        - UPPER_CASE
    - selector: typeLike
      format:
        - PascalCase
  "@typescript-eslint/no-base-to-string":
    - error
    - ignoredTypeNames:
        - RegExp
        - boolean
  "@typescript-eslint/no-confusing-non-null-assertion": error
  "@typescript-eslint/no-confusing-void-expression":
    - error
    - ignoreArrowShorthand: true
  "@typescript-eslint/no-dupe-class-members": error
  "@typescript-eslint/no-duplicate-enum-values": error
  "@typescript-eslint/no-dynamic-delete": error
  "@typescript-eslint/no-empty-function":
    - error
    - allow:
        - arrowFunctions
  "@typescript-eslint/no-extra-non-null-assertion": error
  #"@typescript-eslint/no-extra-parens": error
  "@typescript-eslint/no-extra-semi": error
  "@typescript-eslint/no-extraneous-class":
    - error
    - allowConstructorOnly: true
      allowWithDecorator: true
  "@typescript-eslint/no-for-in-array": error
  "@typescript-eslint/no-implicit-any-catch": error
  "@typescript-eslint/no-implied-eval": error
  "@typescript-eslint/no-invalid-this": error
  "@typescript-eslint/no-invalid-void-type": error
  "@typescript-eslint/no-loop-func": error
  "@typescript-eslint/no-loss-of-precision": error
  "@typescript-eslint/no-magic-numbers":
    - error
    - ignoreReadonlyClassProperties: true
      ignoreArrayIndexes: true
      enforceConst: true
      ignore:
        - 0
        - 1
        - -1
  "@typescript-eslint/no-meaningless-void-operator": error
  "@typescript-eslint/no-non-null-asserted-nullish-coalescing": error
  "@typescript-eslint/no-non-null-asserted-optional-chain": error
  "@typescript-eslint/no-redundant-type-constituents": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-restricted-imports":
    - error
    - allowTypeImports: true
  "@typescript-eslint/no-shadow": error
  "@typescript-eslint/no-this-alias": error
  "@typescript-eslint/no-throw-literal": error
  "@typescript-eslint/no-unsafe-argument": error
  "@typescript-eslint/no-unsafe-assignment": error
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": error
  "@typescript-eslint/no-unnecessary-condition":
    - error
    - allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false
  "@typescript-eslint/no-unnecessary-qualifier": error
  "@typescript-eslint/no-unnecessary-type-arguments": error
  "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-unnecessary-type-constraint": error
  # "@typescript-eslint/no-untyped-public-signature": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-useless-empty-export": error
  "@typescript-eslint/non-nullable-type-assertion-style": error
  "@typescript-eslint/object-curly-spacing":
    - error
    - always
  "@typescript-eslint/padding-line-between-statements": error
  "@typescript-eslint/prefer-as-const": error
  "@typescript-eslint/prefer-enum-initializers": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/prefer-literal-enum-member": error
  "@typescript-eslint/prefer-readonly": error
  "@typescript-eslint/prefer-reduce-type-parameter": error
  "@typescript-eslint/prefer-regexp-exec": error
  # "@typescript-eslint/prefer-optional-chain": error
  "@typescript-eslint/prefer-string-starts-ends-with": error
  "@typescript-eslint/prefer-ts-expect-error": error
  "@typescript-eslint/require-array-sort-compare": error
  "@typescript-eslint/require-await": error
  "@typescript-eslint/restrict-plus-operands":
    - error
    - checkCompoundAssignments: true
  "@typescript-eslint/restrict-template-expressions":
    - error
    - allowNumber: true
      allowBoolean: true
      allowNullish: true
  "@typescript-eslint/return-await": error
  "@typescript-eslint/semi": error
  "@typescript-eslint/sort-type-union-intersection-members": error
  "@typescript-eslint/space-before-blocks": error
  "@typescript-eslint/space-before-function-paren":
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  "@typescript-eslint/space-infix-ops": error
  "@typescript-eslint/strict-boolean-expressions": error
  "@typescript-eslint/triple-slash-reference": error
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/unbound-method":
    - error
    - ignoreStatic: true
  #"@typescript-eslint/unified-signatures": error

  cypress/no-force: error
  cypress/assertion-before-screenshot: error
  cypress/no-pause: error

  #deprecation/deprecation: error

  eslint-comments/no-unused-disable: error

  import/no-cycle:
    - error
    - maxDepth: 4
      ignoreExternal: true
  import/no-unresolved:
    - error
    - ignore:
        - "@angular/common/http"
        - "@angular/platform-browser/animations"
        - "@angular/material"


  prefer-arrow/prefer-arrow-functions:
    - error
    - classPropertiesAllowed: false

  regexp/no-missing-g-flag: error
  regexp/prefer-regexp-exec: error

  # https://github.com/cartant/eslint-plugin-rxjs
  rxjs/ban-observables: error
  rxjs/ban-operators: error
  rxjs/finnish:
    - error
    - methods: false
      strict: true
  rxjs/no-async-subscribe: error
  rxjs/no-compat: error
  rxjs/no-connectable: error
  rxjs/no-cyclic-action: error
  rxjs/no-explicit-generics: error
  rxjs/no-ignored-error: error
  rxjs/no-ignored-observable: error
  rxjs/no-subclass: error
  rxjs/no-topromise: error
  rxjs/no-unsafe-catch: error
  rxjs/no-unsafe-first: error
  rxjs/no-unsafe-switchmap: error
  rxjs/prefer-observer: error
  rxjs/suffix-subjects:
    - error
    # bei Properties: "Finnish Notation" statt Suffix "Subject"
    - properties: false
  rxjs/throw-error: error

  # https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/configs/recommended.js
  unicorn/catch-error-name:
    - error
    - name: err
  unicorn/consistent-function-scoping: off
  unicorn/custom-error-definition: error
  unicorn/filename-case: off
  unicorn/import-style:
    - error
    - styles:
        path:
          named: true
  unicorn/no-array-for-each: off
  # cookieStore ist nur bei HTTPS verfuegbar und nicht in jedem Browser
  unicorn/no-document-cookie: off
  unicorn/no-keyword-prefix: error
  unicorn/no-nested-ternary: error
  unicorn/no-object-as-default-parameter: error
  unicorn/no-process-exit: off
  unicorn/no-static-only-class: error
  unicorn/no-unsafe-regex: error
  unicorn/no-unused-properties: error
  unicorn/numeric-separators-style: error
  unicorn/prefer-array-find: error
  unicorn/prefer-array-flat: error
  unicorn/prefer-flat-map: error
  unicorn/prefer-module: error
  unicorn/prefer-node-protocol: error
  #unicorn/prefer-replace-all: error
  unicorn/prefer-switch: error
  unicorn/prevent-abbreviations: off
  unicorn/string-content: error

  # https://eslint.org/docs/rules
  array-bracket-newline:
    - error
    - multiline: true
  array-bracket-spacing: error
  # https://github.com/prettier/eslint-config-prettier#arrow-body-style-and-prefer-arrow-callback
  # https://eslint.org/docs/rules/arrow-body-style
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  # siehe @typescript-eslint/brace-style
  brace-style: 0
  camelcase: error
  # siehe @typescript-eslint/comma-dangle
  comma-dangle: 0
  # siehe @typescript-eslint/comma-spacing
  comma-spacing: 0
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  # https://github.com/prettier/eslint-config-prettier#curly
  # https://eslint.org/docs/rules/curly
  curly:
    - error
    - all
  default-case: error
  default-case-last: error
  default-param-last: error
  # siehe @typescript-eslint/dot-notation
  dot-notation: 0
  eqeqeq: error
  eol-last: error
  for-direction: error
  # siehe @typescript-eslint/func-call-spacing
  func-call-spacing: 0
  func-name-matching: error
  func-names:
    - error
    - never
  func-style: error
  getter-return: error
  grouped-accessor-pairs: error
  handle-callback-err: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style: error
  max-classes-per-file: error
  max-depth: error
  # https://github.com/prettier/eslint-config-prettier#max-len
  # https://eslint.org/docs/rules/max-len
  max-len:
    - error
    - ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
  max-lines: error
  max-lines-per-function:
    - error
    - max: 60
  max-nested-callbacks:
    - error
    - max: 4
  max-params: error
  max-statements:
    - error
    - max: 25
  max-statements-per-line: error
  new-cap: 0
  new-parens: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  # https://github.com/prettier/eslint-config-prettier#no-confusing-arrow
  # https://eslint.org/docs/rules/no-confusing-arrow
  no-confusing-arrow:
    - error
    - allowParens: false
  no-console: 0
  no-constant-binary-expression: error
  no-constructor-return: error
  no-continue: error
  no-dupe-class-members: 0
  # siehe import/no-duplicates
  # no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-empty-static-block: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  # siehe @typescript-eslint/no-extra-semi
  no-extra-semi: 0
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  # siehe @typescript-eslint/no-invalid-this
  no-invalid-this: 0
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  # siehe "@typescript-eslint/no-loss-of-precision": error
  no-loss-of-precision: off
  # siehe @typescript-eslint/no-magic-numbers
  no-magic-numbers: 0
  no-multi-assign: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-native-nonconstructor: error
  no-new-object: error
  no-new-wrappers: error
  no-nonoctal-decimal-escape: error
  no-param-reassign: error
  no-proto: error
  # siehe @typescript-eslint/no-restricted-imports
  no-restricted-imports: 0
  no-restricted-properties: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  # siehe @typescript-eslint/no-shadow
  no-shadow: 0
  no-shadow-restricted-names: error
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle:
    - error
    - allow:
        - _id
        - __v
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unsafe-optional-chaining: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-use-before-define:
    - error
    - functions: false
      classes: false
  no-useless-backreference: error
  no-useless-call: error
  no-useless-catch: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-void: error
  no-whitespace-before-property: error
  no-with: error
  nonblock-statement-body-position: error
  object-curly-newline:
    - error
    - multiline: true
  # siehe @typescript-eslint/object-curly-spacing
  object-curly-spacing: 0
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-shorthand: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-numeric-literals: error
  prefer-object-has-own: error
  prefer-object-spread: error
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  prefer-rest-params: error
  prefer-template: error
  # angular-eslint recommended
  #quote-props: error
  # angular-eslint recommended
  # https://github.com/prettier/eslint-config-prettier#quotes
  # https://eslint.org/docs/rules/quotes
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  radix: error
  require-atomic-updates: error
  require-await: error
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi-spacing: error
  sort-imports: error
  space-before-blocks: error
  # siehe @typescript-eslint/space-before-function-paren
  space-before-function-paren: 0
  space-in-parens: error
  # siehe @typescript-eslint/space-infix-ops
  space-infix-ops: 0
  space-unary-ops: error
  spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  wrap-iife: error
  yield-star-spacing: error
  yoda:
    - error
    - never

overrides:
  - files:
      - "*.component.html"
    parser: "@angular-eslint/template-parser"
    plugins:
      - "@angular-eslint/template"
    rules:
      "@angular-eslint/template/accessibility-label-for": error
      "@angular-eslint/template/accessibility-label-has-associated-control": error
      "@angular-eslint/template/accessibility-table-scope": error
      "@angular-eslint/template/accessibility-valid-aria": error
      "@angular-eslint/template/conditional-complexity": error
      "@angular-eslint/template/cyclomatic-complexity": error
      "@angular-eslint/template/eqeqeq": error
      "@angular-eslint/template/no-any": error
      "@angular-eslint/template/no-autofocus": error
      "@angular-eslint/template/no-duplicate-attributes": error
