# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#                                       $env:TAG = '1.0.0'
#           skaffold dev

apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kundeweb
build:
  artifacts:
    - image: docker.io/gruppe2/kundeweb
  local: {}
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
deploy:
  kustomize:
    paths: [extras/kustomize/overlays/prod]
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      kustomize:
        paths: [extras/kustomize/overlays/dev]
        flags:
          disableValidation: true
    portForward:
      - resourceType: service
        resourceName: kundeweb
        port: 80
